version: '3.8'

services:
  frontend:
    build: .
    container_name: ges_frontend
    restart: always
    ports:
      - "80:80"
    networks:
      - ges_network

networks:
  ges_network:
    external: true
